version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: "host"
    depends_on:
      - api-gateway
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d

  api-gateway:
    build:
      context: api-gateway
      target: api-gateway
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=7070
      - LOG_LVL=info
    ports:
        - "7070-7072:7070"
